#!/usr/bin/env python3
"""Produce ML_REPORT.md and its figure from ml/results/.

Run `python ml/train.py` first.
"""
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
RES = ROOT / "ml" / "results" / "results_eraB.csv"
FIG = ROOT / "analysis" / "figures"
OUT = ROOT / "ML_REPORT.md"

SURFACE, INK, INK2, MUTED, GRID = "#fcfcfb", "#0b0b0b", "#52514e", "#898781", "#e1e0d9"
COLOURS = {"persistence": "#898781", "historical average": "#b07a12",
           "seasonal naive": "#c0442c", "ridge": "#9ec5f4",
           "xgboost": "#2a78d6", "lstm": "#0d8a66"}
ORDER = ["persistence", "historical average", "seasonal naive", "ridge", "xgboost", "lstm"]


def bare(ax):
    for s in ax.spines.values():
        s.set_visible(False)
    ax.tick_params(colors=MUTED, labelsize=8)


def figure(df):
    fig, axes = plt.subplots(1, 3, figsize=(14, 4.4))
    fig.patch.set_facecolor(SURFACE)
    panels = [("MAE", "Overall MAE — all test rows"),
              ("rush_MAE", "Rush-hour MAE — 08–12 and 17–22 IST"),
              ("rush_F1", "Congestion F1 in rush hour (higher is better)")]
    for ax, (col, title) in zip(axes, panels):
        for m in ORDER:
            s = df[df.model == m].sort_values("horizon_min")
            if not len(s):
                continue
            ax.plot(s.horizon_min, s[col], "o-", color=COLOURS[m], lw=2.2,
                    ms=5, label=m)
        ax.set_xticks([30, 60, 90])
        ax.set_xlabel("forecast horizon (minutes ahead)", color=INK2, fontsize=9)
        ax.grid(axis="y", color=GRID, lw=0.5)
        ax.set_axisbelow(True)
        bare(ax)
        ax.set_title(title, color=INK, fontsize=10, loc="left")
    axes[0].set_ylabel("mean absolute error", color=INK2, fontsize=9)
    # legend under the panels: inside the axes it sat on top of the
    # seasonal-naive line in the left panel.
    h, l = axes[0].get_legend_handles_labels()
    fig.legend(h, l, frameon=False, fontsize=8.5, labelcolor=INK2,
               loc="lower center", ncol=6, bbox_to_anchor=(0.5, -0.02))
    fig.suptitle("Forecasting Mumbai speed ratio — models vs baselines",
                 color=INK, fontsize=13, x=0.01, ha="left")
    fig.tight_layout(rect=(0, 0.07, 1, 0.94))
    FIG.mkdir(parents=True, exist_ok=True)
    fig.savefig(FIG / "ml_models.png", dpi=150, facecolor=SURFACE)
    plt.close(fig)


def table(df, cols, labels):
    head = "| model | " + " | ".join(labels) + " |"
    # separator must match the HEADER width (one label per horizon), not the
    # number of source columns -- a mismatch makes markdown skip the table and
    # dump raw pipes into the text.
    sep = "|---" * (len(labels) + 1) + "|"
    rows = [head, sep]
    for m in ORDER:
        s = df[df.model == m].sort_values("horizon_min")
        if not len(s):
            continue
        vals = []
        for c in cols:
            vals += [f"{v:.4f}" if "MAE" in c or "RMSE" in c else f"{v:.3f}"
                     for v in s[c]]
        name = f"**{m}**" if m == "lstm" else m
        rows.append(f"| {name} | " + " | ".join(vals) + " |")
    return "\n".join(rows)


def main():
    df = pd.read_csv(RES)
    figure(df)

    best = df.loc[df.groupby("horizon_min")["MAE"].idxmin()]
    gains = {int(r.horizon_min): r.vs_persistence_pct for r in best.itertuples()}
    lstm = df[df.model == "lstm"].set_index("horizon_min")
    pers = df[df.model == "persistence"].set_index("horizon_min")

    md = f"""# Forecasting Mumbai traffic — model report

Can the next hour of Mumbai traffic be predicted from the data this project
collected? Short answer: **yes, and an LSTM does it best** — but only once it is
compared against baselines that are genuinely hard to beat.

Generated by `ml/train.py` and `ml/report_ml.py`.

## The task

Given a monitoring point's last 3 hours of speed ratio, predict that point's
ratio **30, 60 and 90 minutes ahead**. One step is 30 minutes, matching the
collection cadence.

Trained on era B: **50 points, 868 time steps, ~33,700 training samples**
(all points pooled into one model).

### Why the split matters

Train on the earliest 80% of time steps, test on the latest 20%. Concretely:
train ends 5 Sept 06:00, test covers 5–8 Sept. A random split would let the
model see the future and every score below would be meaningless.

### An honest note on scale

The standard benchmarks in this field — METR-LA and PEMS-BAY — carry 34,000+
time steps from 200+ sensors over 4–5 months. This dataset has **868 time
steps**, roughly 40× less history. Spatio-temporal graph networks (DCRNN,
Graph WaveNet) are built for that larger regime and would overfit here, so the
model set is deliberately kept to methods that suit the data volume.

## Baselines, and why they are not a formality

Traffic is highly autocorrelated: 30 minutes from now usually looks like now.
That makes **persistence** a strong baseline, and plenty of published models
fail to beat it at short horizons. Three baselines are used:

| baseline | rule |
|---|---|
| persistence | the value stays where it is |
| historical average | that point, that hour, weekday vs weekend (computed on train only) |
| seasonal naive | the same clock time yesterday |

## Results

![models vs baselines](analysis/figures/ml_models.png)

### Overall error (lower is better)

{table(df, ["MAE"], ["MAE 30 min", "MAE 60 min", "MAE 90 min"])}

The LSTM wins at every horizon, and — importantly — **its margin grows with
horizon**: {gains.get(30,0):+.0f}% better than persistence at 30 minutes,
{gains.get(60,0):+.0f}% at 60, {gains.get(90,0):+.0f}% at 90. That is the
expected shape: persistence decays as you look further ahead, a learned model
holds up.

### But overall MAE flatters everyone

Only **3% of test targets are congested**. Most rows are a free-flowing road at
night, where predicting "1.00 stays 1.00" is trivial. The honest test is rush
hour and already-slow roads:

{table(df, ["rush_MAE"], ["rush MAE 30", "rush MAE 60", "rush MAE 90"])}

The ranking survives. LSTM rush-hour MAE is
{lstm.loc[30,'rush_MAE']:.4f} / {lstm.loc[60,'rush_MAE']:.4f} / {lstm.loc[90,'rush_MAE']:.4f}
against persistence at
{pers.loc[30,'rush_MAE']:.4f} / {pers.loc[60,'rush_MAE']:.4f} / {pers.loc[90,'rush_MAE']:.4f}
— a {(1-lstm.loc[30,'rush_MAE']/pers.loc[30,'rush_MAE'])*100:.0f}% to
{(1-lstm.loc[90,'rush_MAE']/pers.loc[90,'rush_MAE'])*100:.0f}% improvement.

### Calling the jam

Regression error is not what a commuter cares about. Treating "ratio below 0.5"
as a congestion alarm:

{table(df, ["rush_F1"], ["F1 30 min", "F1 60 min", "F1 90 min"])}

Around **0.5 F1** — useful, not solved. The models are better at precision than
recall: when they call a jam they are usually right, but they miss roughly half
of them. Sudden-onset jams are exactly what 30-minute sampling cannot see
coming.

## Three findings worth keeping

1. **The LSTM's advantage is real but modest, and it grows with horizon.**
   At 30 minutes persistence is nearly as good; by 90 minutes the gap is clear.
   Anyone claiming a large short-horizon win over persistence should be asked
   what their baseline was.
2. **Historical average is remarkably strong.** It ignores current conditions
   entirely, yet beats persistence from 60 minutes out. Mumbai traffic is
   highly routine — the clock predicts congestion better than the present does,
   once you look far enough ahead.
3. **On already-slow roads, XGBoost edges out the LSTM at 60 and 90 minutes**
   ({df[(df.model=='xgboost')&(df.horizon_min==90)].slow_MAE.iloc[0]:.4f} vs
   {df[(df.model=='lstm')&(df.horizon_min==90)].slow_MAE.iloc[0]:.4f}). The
   LSTM wins on average; it is not uniformly better.

## Limitations

- **868 time steps.** Enough for these models, not enough for spatio-temporal
  graph networks. More collection is the single biggest available improvement.
- **One test window** (5–8 Sept). No repeated cross-validation across folds, so
  treat the margins as indicative rather than precise.
- **Spatial structure is barely used.** Only a `neighbour_mean` feature; the
  adjacency graph built in `adjacency.csv` is not exploited by a real graph
  model, because the data volume does not support one.
- **The LSTM is optimised for MAE** (L1 loss), so it wins on MAE while XGBoost
  sometimes wins on RMSE. That is a consequence of the objective, not evidence
  of a better model.
- Speed ratio depends on TomTom's modelled free-flow baseline, not a measured
  overnight speed.

## Reproducing

```bash
python ml/dataset.py       # dataset shapes and feature list
python ml/train.py         # trains everything, writes ml/results/
python ml/report_ml.py     # this report and its figure
```
"""
    OUT.write_text(md, encoding="utf-8")
    print(f"wrote {OUT}")
    print(f"figure -> {FIG / 'ml_models.png'}")


if __name__ == "__main__":
    main()
